### ISSUE TITLE
Update Extracted Features API queries based on newly ingested aggregate data

### ISSUE THREAD

**Issue by jswatsch** [htrc/HTRC-EF-API#4]
Create a new endpoint in EF-API, to get workset volumes by workset ID using the new aggregated features collection.

**Comment by jswatsch** [comment]
@samithaliyanage and @sandeep-ps are investigating the API code.

**Comment by jswatsch** [comment]
@sandeep-ps is working on updating the Extracted Features API to get data from the new aggregate data collection.

- Will be creating a new endpoint

**Comment by sandeep-ps** [comment]
Hi, @jswatsch, I'm transferring this issue to the EF-API repo. I hope that's okay. We can always move it back if you prefer that way. Thanks.
